# Generated by Django 2.0.3 on 2018-03-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
                ('capacity', models.CharField(max_length=20)),
                ('type_room', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('course_style', models.CharField(max_length=100)),
            ],
        ),
    ]
