# Generated by Django 2.0.2 on 2018-02-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=20),
        ),
    ]
