# Generated by Django 2.0.2 on 2018-02-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PregenSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulingElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferenceOrConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scheduler.SchedulingElement')),
                ('next_block', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_block', to='scheduler.Block')),
                ('paired_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paired_with_reverse', to='scheduler.Block')),
            ],
            bases=('scheduler.schedulingelement',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scheduler.SchedulingElement')),
                ('section_count', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Division')),
            ],
            bases=('scheduler.schedulingelement',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scheduler.SchedulingElement')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Division')),
            ],
            bases=('scheduler.schedulingelement',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scheduler.SchedulingElement')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Division')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.RoomType')),
            ],
            bases=('scheduler.schedulingelement',),
        ),
        migrations.CreateModel(
            name='UserConstaint',
            fields=[
                ('userpreferenceorconstraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.UserPreferenceOrConstraint')),
            ],
            bases=('scheduler.userpreferenceorconstraint',),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('userpreferenceorconstraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.UserPreferenceOrConstraint')),
                ('score', models.IntegerField()),
            ],
            bases=('scheduler.userpreferenceorconstraint',),
        ),
        migrations.AddField(
            model_name='userpreferenceorconstraint',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduler.SchedulingElement'),
        ),
        migrations.AddField(
            model_name='userpreferenceorconstraint',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduler.SchedulingElement'),
        ),
        migrations.AddField(
            model_name='hunk',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Course'),
        ),
        migrations.AddField(
            model_name='pregensection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Course'),
        ),
        migrations.AddField(
            model_name='hunk',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Block'),
        ),
        migrations.AddField(
            model_name='hunk',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Professor'),
        ),
        migrations.AddField(
            model_name='hunk',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Room'),
        ),
    ]
