# Generated by Django 2.0.2 on 2018-02-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserConstaint',
            new_name='UserConstraint',
        ),
    ]
