# Generated by Django 2.0.2 on 2018-02-28 19:32

from django.db import migrations, models
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20180228_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(default=scheduler.models.Room.building_default, max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=scheduler.models.Room.room_number_default),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_number', 'building')},
        ),
    ]
