# Generated by Django 2.0.2 on 2018-02-28 21:24

from django.db import migrations, models
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20180228_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='name',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='identifier',
            field=models.CharField(default=scheduler.models.Course.identifier_default, max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='ins_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(default=scheduler.models.Course.program_default, max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='section_capacity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='division',
            field=models.CharField(default=scheduler.models.Division.division_default, max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='style',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='subject',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(default=scheduler.models.RoomType.room_type_default, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='section_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('program', 'identifier')},
        ),
    ]
