# Generated by Django 2.0.2 on 2018-02-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20180228_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='professor_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='first',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='last',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
