# Generated by Django 2.0.2 on 2018-03-02 18:01

from django.db import migrations, models
import django.db.models.deletion
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20180228_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor_courses',
            old_name='course',
            new_name='identifier',
        ),
        migrations.AddField(
            model_name='professor_courses',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Professor'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.PositiveIntegerField(default=scheduler.models.Block.block_default),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(default=scheduler.models.Room.room_number_default),
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'room_number')},
        ),
    ]
