# Generated by Django 2.0.2 on 2018-03-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20180302_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintPreferenceList',
            fields=[
                ('constriant', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='professor_courses',
            new_name='ProfessorCourses',
        ),
        migrations.RemoveField(
            model_name='hunk',
            name='block',
        ),
        migrations.RemoveField(
            model_name='hunk',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='hunk',
            name='room',
        ),
        migrations.RemoveField(
            model_name='hunk',
            name='section',
        ),
        migrations.RemoveField(
            model_name='pregensection',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userconstraint',
            name='left_argument_type',
        ),
        migrations.RemoveField(
            model_name='userconstraint',
            name='right_argument_type',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='left_argument_type',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='right_argument_type',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='suffix',
            new_name='section_identifier',
        ),
        migrations.DeleteModel(
            name='Hunk',
        ),
        migrations.DeleteModel(
            name='PregenSection',
        ),
        migrations.DeleteModel(
            name='UserConstraint',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
