# Generated by Django 2.0.2 on 2018-03-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scheduler', '0008_auto_20180305_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PregenSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_argument_id', models.PositiveIntegerField()),
                ('right_argument_id', models.PositiveIntegerField()),
                ('is_blacklist', models.BooleanField()),
                ('left_argument_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('right_argument_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_argument_id', models.PositiveIntegerField()),
                ('right_argument_id', models.PositiveIntegerField()),
                ('score', models.IntegerField()),
                ('left_argument_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('right_argument_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ConstraintPreferenceList',
        ),
        migrations.AddField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregensection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Course'),
        ),
        migrations.AddField(
            model_name='hunk',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Block'),
        ),
        migrations.AddField(
            model_name='hunk',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Professor'),
        ),
        migrations.AddField(
            model_name='hunk',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Room'),
        ),
        migrations.AddField(
            model_name='hunk',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Section'),
        ),
    ]
