# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
