# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='day',
        ),
        migrations.RemoveField(
            model_name='block',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='block',
            name='start_time',
        ),
    ]
